export default function TermsAndConditionsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 bg-white">
      <div className="space-y-6 text-gray-700 leading-relaxed">
        <section>
          <p className="mb-4">
        TERMS AND CONDITIONS – PARTS NOW
          </p>
          <p className="mb-4">
        This document is an electronic record in terms of the Information Technology Act, 2000 and the rules made thereunder, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p className="mb-4">
        This document is published in accordance with Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, requiring publication of rules and regulations, privacy policy, and terms of use for access or usage of a website, mobile site, or mobile application. It governs the access and use of the mobile application, website, and backend portal operated under the name "Parts Now" ("Platform"), owned and operated by ESOFT AUTO PRIVATE LIMITED ("Company", "we", "us", or "our").
          </p>
          <p className="mb-4">
        By accessing, browsing, registering on, or otherwise using the Platform, you ("User", "you", or "your") agree to be bound by these Terms and Conditions ("Terms of Use" or "Terms"), along with all policies referenced here (including the Privacy Policy, Refund/Return Policy, Shipping Policy, and any specific product/service terms). If you do not agree to these Terms, you must not use the Platform or any of the Services.
          </p>
          <p className="mb-4">
        These Terms constitute a legally binding agreement between you and the Company for use of the Platform and related services, including access to our parts marketplace, ordering services, AI-powered tools, workshop dashboards, and garage management software (collectively, "Services").
          </p>
          <p className="mb-4">
        The area of jurisdiction for all disputes arising out of or in connection with these Terms shall be Indore, Madhya Pradesh, India, and these Terms shall be governed by the laws of India.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">1. Eligibility and Registration</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>You must be a natural or legal person competent to contract under the Indian Contract Act, 1872 to use the Platform.</li>
        <li>The Platform is primarily intended for garage and workshop owners and their authorised representatives who procure automotive parts or use workshop management tools.</li>
        <li>When you create an account, you agree to provide true, accurate, current, and complete information (including business name, GSTIN, address, contact details) and keep it updated.</li>
        <li>You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account; any activity from your account will be deemed authorised by you.</li>
        <li>We reserve the right to refuse registration, suspend, or terminate your account at our sole discretion, including for suspected fraud, misrepresentation, or violation of these Terms or applicable law.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">2. Scope of Services</h2>
          <p className="mb-3">The Platform provides, among other things:</p>
          <ul className="list-disc list-inside space-y-2">
        <li>A B2B spare parts and accessories marketplace connecting workshops with OEMs and authorised distributors for automotive parts and car accessories.</li>
        <li>Negotiated procurement services where we act as an intermediary to obtain competitive pricing and optimal delivery times from our supplier network.</li>
        <li>Doorstep delivery of parts to workshops through in-house and third-party logistics partners.</li>
        <li>AI-powered ordering tools, including voice-based ordering, number-plate-based lookup, image-based part and vehicle detection, and intelligent catalog search.</li>
        <li>A workshop dashboard showing jobs executed, turnaround time, and performance KPIs, and a garage management software for day-to-day operations.</li>
        <li>Digital marketing and promotional services to increase workshop visibility and customer footfall (e.g., ads, online promotions).</li>
        <li>Services may be updated, modified, or discontinued from time to time at our discretion.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">3. Platform Access and Acceptable Use</h2>
          <p className="mb-3">By using the Platform, you agree that you will:</p>
          <ul className="list-disc list-inside space-y-2">
        <li>Use the Platform only for legitimate business purposes related to your workshop or garage operations.</li>
        <li>Not use the Platform for any purpose that is unlawful, illegal, or forbidden by these Terms or by any applicable law or regulation.</li>
        <li>Not attempt to gain unauthorized access to any portion or feature of the Platform, or to any systems or networks connected to the Platform.</li>
        <li>Not engage in activities such as data scraping, reverse engineering, introducing viruses/malware, or any action that may impair the performance or security of the Platform.</li>
        <li>Not upload or transmit any content that is defamatory, obscene, infringing, fraudulent, or otherwise objectionable or illegal.</li>
        <li>Any unauthorised use of the Platform may result in suspension or termination of access and/or legal action.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">4. Ordering, Pricing, Payments and Delivery</h2>
          <div className="space-y-4">
        <div>
          <h3 className="font-semibold mb-2">4.1 Orders and Contracts</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>When you place an order for parts or services on the Platform, you make a binding offer to purchase those items in accordance with these Terms and the specific product/service terms shown at checkout.</li>
            <li>Order confirmation (via app/website or email/SMS) constitutes acceptance of your offer and forms a binding contract between you and the Company.</li>
          </ul>
        </div>
        <div>
          <h3 className="font-semibold mb-2">4.2 Pricing and Availability</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>Prices, taxes, delivery charges, and applicable fees will be displayed at or before checkout; they may vary by location, supplier, and availability.</li>
            <li>We strive to offer wholesale/distributor-level pricing leveraging our OEM partnerships and distributor network, but final prices remain subject to market conditions and supplier terms.</li>
            <li>Availability of parts and delivery timelines are subject to stock status and logistics constraints; we do not guarantee continuous availability or specific delivery times, though we aim for the fastest possible delivery.</li>
          </ul>
        </div>
        <div>
          <h3 className="font-semibold mb-2">4.3 Payments</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>Payments for orders shall be made through authorized payment methods integrated on the Platform, including Razorpay or other payment aggregators as applicable.</li>
            <li>By initiating a transaction, you authorise the payment gateway and the Company to process your payment in accordance with RBI and payment aggregator guidelines.</li>
            <li>Any payment disputes, chargebacks, or failed transactions will be handled as per the payment gateway and our internal policies; you may be required to provide supporting documentation.</li>
          </ul>
        </div>
        <div>
          <h3 className="font-semibold mb-2">4.4 Delivery</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>Parts will be delivered through a combination of our own logistics and third-party delivery partners, as indicated during checkout.</li>
            <li>Risk of loss passes to you upon delivery of the goods at the address provided by you or upon handover to your authorised representative.</li>
            <li>Delays due to circumstances beyond our control (traffic, weather, supplier delays, force majeure) do not entitle automatic cancellation or compensation, except as provided in our Refund/Return Policy.</li>
          </ul>
        </div>
        <div>
          <h3 className="font-semibold mb-2">4.5 Returns, Cancellations, and Refunds</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>Returns, cancellations, and refunds will be governed by our Refund/Return Policy published on the Platform, which should specify timelines (e.g., within 5–7 working days for approved refunds) and conditions (e.g., unused, in original packaging, non-electrical parts only, etc.).</li>
            <li>Certain items (e.g., electrical parts, special-order items, customised items) may be non-returnable; such conditions will be indicated wherever reasonably possible.</li>
          </ul>
        </div>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">5. Use of AI, Dashboards and Garage Management Software</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>The Platform includes AI-powered tools (voice ordering, image-based detection, number-plate-based lookup, recommendations) intended to assist in faster and more accurate part identification and ordering.</li>
        <li>These tools rely on available data and algorithms and do not constitute professional advice or a guarantee of suitability or compatibility; you remain responsible for verifying that ordered parts are appropriate for the vehicle and job.</li>
        <li>Workshop dashboards and analytics are provided for informational purposes to help track jobs, turnaround time, and other KPIs; accuracy may depend on the data you input and third-party data sources.</li>
        <li>Garage management features (job tracking, billing, task management, etc.) are offered under a SaaS or subscription model; your use of these features may be subject to specific plan terms, usage limits, and fees displayed on the Platform.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">6. Subscriptions, SaaS and Value-Added Services</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>We may offer subscription plans (monthly/annual) that provide access to advanced features, such as detailed analytics dashboards, multi-user access, invoicing tools, priority support, or premium AI insights.</li>
        <li>Plan inclusions, pricing, and billing cycles will be described at the point of subscription; by subscribing, you authorise recurring billing as per the chosen plan until cancelled in accordance with the applicable subscription terms.</li>
        <li>Optional digital marketing services (e.g., online ads, social media promotion, local SEO for workshops) and other value-added services (priority delivery, premium catalog access, partner services) may be offered on a pay-per-use or package basis.</li>
        <li>We may earn commissions from partners (e.g., insurers, financiers, logistics providers) for referrals; details will be provided in relevant service descriptions or partner-specific terms.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">7. Third-Party Links and Services</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>The Platform may contain links to third-party websites, applications, or services, including payment gateways, logistics providers, marketing platforms, and other partners.</li>
        <li>When you access such third-party services, you may be subject to their separate terms of use, privacy policies, and other policies, which you are responsible for reviewing.</li>
        <li>We do not control, endorse, or assume responsibility for third-party content, products, or services, and your use of them is at your sole risk.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">8. Intellectual Property Rights</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>All rights, title, and interest in and to the Platform, including but not limited to software, code, AI models, design, layout, look and feel, graphics, logos, trademarks, service marks, text, images, and other content, are owned by or licensed to the Company.</li>
        <li>Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable licence to access and use the Platform and Services solely for your internal business operations as a workshop/garage.</li>
        <li>You shall not reproduce, distribute, modify, create derivative works of, publicly display, or commercially exploit any part of the Platform, except as expressly permitted by us in writing.</li>
        <li>Any feedback, suggestions, or ideas you submit may be used by us to improve the Platform and Services without obligation to compensate you.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">9. Data Protection and Privacy</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>Our Privacy Policy – Parts Now describes how we collect, use, store, share, and protect personal, business, and technical data, including voice recordings, images, and usage data.</li>
        <li>By using the Platform, you acknowledge and agree that your data will be processed in accordance with the Privacy Policy and applicable data protection laws.</li>
        <li>You are responsible for ensuring that any personal data you provide to us (e.g., customer details entered into the garage management system) has been collected and shared in compliance with applicable law.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">10. Charges and Taxes</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>You agree to pay all charges associated with availing the Services, including product prices, subscription fees, delivery charges, and any applicable taxes (such as GST) as displayed on the Platform at the time of transaction.</li>
        <li>Prices and fees may be updated from time to time at our discretion, and such changes will apply prospectively from the date of update.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">11. Disclaimers</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>The Platform and Services are provided on an "as is" and "as available" basis without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.</li>
        <li>We do not warrant that the Platform will be uninterrupted, timely, secure, or error-free, or that any defects will be corrected.</li>
        <li>We do not guarantee the accuracy, completeness, or suitability of any information, recommendations, or materials provided on the Platform for any specific purpose; you are required to independently assess whether the Services meet your requirements.</li>
        <li>Any reliance you place on such information and materials is strictly at your own risk and discretion.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">12. Limitation of Liability</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>To the fullest extent permitted by law, in no event shall the Company, its directors, employees, agents, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, business interruption, or loss of data, arising out of or in connection with your use of the Platform or Services.</li>
        <li>Our aggregate liability, whether in contract, tort, or otherwise, for any claims arising out of or relating to these Terms or your use of the Platform shall not exceed the amount paid by you to us for the specific order or subscription giving rise to the claim, or INR 5,000, whichever is lower.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">13. Indemnity</h2>
          <p className="mb-3">You agree to indemnify and hold harmless the Company, its affiliates, group companies, and their respective officers, directors, agents, and employees from and against any and all claims, demands, actions, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising out of or in connection with:</p>
          <ul className="list-disc list-inside space-y-2">
        <li>Your use of the Platform or Services.</li>
        <li>Your breach of these Terms, the Privacy Policy, or any other applicable policies.</li>
        <li>Your violation of any applicable law, regulation, or rights of a third party (including intellectual property rights).</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">14. Force Majeure</h2>
          <p className="mb-3">
        Notwithstanding anything contained in these Terms, we shall not be liable for any failure to perform or delay in performance of any obligation where such failure or delay results from events beyond our reasonable control, including but not limited to acts of God, natural disasters, epidemics, strikes, labour disputes, war, civil disturbance, governmental actions, interruption of utilities, or failures of networks or communications ("Force Majeure Event").
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">15. Modifications to Terms and Services</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>We reserve the right to modify, update, or replace these Terms (in whole or in part) at any time without prior notice, subject to applicable law.</li>
        <li>It is your responsibility to periodically review the Terms to stay informed of updates; your continued use of the Platform after any modification constitutes your acceptance of the revised Terms.</li>
        <li>We may also modify, suspend, or discontinue any part of the Services with or without notice, without any liability to you.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">16. Governing Law and Jurisdiction</h2>
          <ul className="list-disc list-inside space-y-2">
        <li>These Terms, and any dispute or claim relating to them or their enforceability, shall be governed by and construed in accordance with the laws of India.</li>
        <li>All disputes arising out of or in connection with these Terms, the Platform, or the Services shall be subject to the exclusive jurisdiction of the courts at Indore, Madhya Pradesh, India only.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">17. Grievances and Contact Information</h2>
          <p className="mb-3">For any questions, complaints, or concerns regarding these Terms, the Platform, or the Services, you may contact us at:</p>
          <div className="bg-gray-100 p-4 rounded">
        <p><strong>Email:</strong> esoftauto@gmail.com</p>
        <p><strong>Grievance Officer:</strong> Anil Shah</p>
        <p><strong>Company:</strong> ESOFT AUTO PRIVATE LIMITED</p>
        <p><strong>Address:</strong> Plot no. 420, New Loha Mandi, Scheme no. 78, Phase 2, NIRANJANPUR, DEWAS NAKA, INDORE, MADHYA PRADESH 452010, Indore, Madhya Pradesh, India</p>
        <p className="mt-3">We will endeavour to acknowledge and respond to your concerns within the time limits prescribed under applicable law.</p>
          </div>
        </section>
      </div>
    </main>
  );
}
